# Generated by Django 4.1.3 on 2022-11-22 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("currency", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bought",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Buyer",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sold",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Seller",
            ),
        ),
    ]
