# Generated by Django 4.1.3 on 2022-11-28 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0003_remove_deal_seller_remove_offer_user_offer_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="offer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="currency.offer",
                verbose_name="Offer",
            ),
        ),
    ]
