# Generated by Django 4.1.3 on 2022-11-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0003_remove_deal_seller_remove_offer_user_offer_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=11, verbose_name="Amount"
            ),
            preserve_default=False,
        ),
    ]
